"""Domain reference data for procurement audits."""
from __future__ import annotations

from typing import List, TypedDict


class StepChecklist(TypedDict):
    step: int
    title: str
    description: str
    checkpoints: List[str]
    world_bank_alignment: List[str]


BPP_NINE_STEPS: List[StepChecklist] = [
    {
        "step": 1,
        "title": "Efficient procurement plan driven by needs assessment",
        "description": "Validates that every procurement initiative starts with a defensible needs statement and structured market strategy.",
        "checkpoints": [
            "Assess the process for identification and justification of the requirement",
            "Analyse the stakeholder management analysis and review",
            "Review the critical needs analysis assessment",
            "Analyse the detailed specification for suitability, openness, and objectivity",
            "Evaluate the strategic analysis process",
            "Assess feasibility and affordability exploration",
            "Assess the process for choosing contract type, structure, and duration",
            "Assess the tender process adopted",
            "Review schedule requirements, milestones, and financing dates",
            "Evaluate the quality expectations set",
            "Assess the risk analysis including appetite, impact, probability, and influencers",
            "Validate the project or contract personnel assigned",
            "Review the market analysis and supplier identification process",
            "Evaluate responsibility matrices, sign-offs, delegations, and RACI formats",
            "Assess geographical or locality issues affecting the contract",
            "Ensure metrics and data sources are clearly identified",
            "Assess reporting and compliance objectives and activities",
            "Analyse ethical compliance considerations and responsibilities",
            "Verify other pertinent or bespoke factors affecting the requirement",
        ],
        "world_bank_alignment": ["Generate Strategy", "Plan Procurement"],
    },
    {
        "step": 2,
        "title": "Budget / Appropriation",
        "description": "Ensures the budget model is evidence-based, validated, and aligned with finance policies and anti-corruption expectations.",
        "checkpoints": [
            "Review the detailed cost model and verify its time validity",
            "Verify authorship and challenge of the model",
            "Assess total cost evaluation, pricing strategy, price security, and VFM factors",
            "Assess whether the model is static, fluid, or future focused",
            "Verify source data and the cost-modelling technique",
            "Assess margins of error, stability parameters, and forecast variance",
            "Evaluate the model against previous models, similar contracts, and experience",
            "Analyse the included cost drivers",
            "Examine currency, levy, tariff, and other international factors",
            "Verify signatures and counter-verification",
            "Verify compliance with finance policies of government and other bodies",
            "Evaluate financial management, accounting, and reporting processes",
            "Assess post-award and post-contract variance along with root-cause analysis",
            "Assess application of anti-corruption, ethical, and World Bank requirements",
            "Analyse the budget process assessment and review cadence",
        ],
        "world_bank_alignment": ["Plan Procurement"],
    },
    {
        "step": 3,
        "title": "Advertisement / Invitation to tender",
        "description": "Confirms opportunity publication is transparent, inclusive, and compliant with equality legislation.",
        "checkpoints": [
            "Analyse the advertisement for clarity, compliance, and openness",
            "Ensure inclusion of all relevant requirement elements",
            "Check compliance with equity, equality, and openness requirements",
            "Verify opportunity publication process, timings, and effectiveness",
            "Verify publication channels such as media, newspapers, and web portals",
            "Verify language and equity requirements were satisfied",
            "Assess management of expressions of interest and pre-approved bidder lists",
        ],
        "world_bank_alignment": ["Invite Offers"],
    },
    {
        "step": 4,
        "title": "Transparent prequalification",
        "description": "Evaluates whether prequalification processes remain objective, time-bound, and well communicated.",
        "checkpoints": [
            "Evaluate the predetermined assessment strategy",
            "Assess criteria for openness and objectivity",
            "Verify publication of the prequalification process and boundaries",
            "Assess data and information sources used for review",
            "Review assessment process, criteria, consistency, and calculations",
            "Assess the quality of evidence provided",
            "Determine if objective criteria were enforced",
            "Analyse prequalification team makeup, structure, and governance",
            "Assess supplier qualification and shortlisting process",
            "Assess requalification records and reporting",
            "Assess query handling, dialogue management, and publicity obligations",
            "Verify issuing methods, ethical management, and information controls",
            "Assess supplier notification style, timing, and content",
            "Assess whether right-of-appeal or resubmission details were provided",
        ],
        "world_bank_alignment": ["Invite Offers", "Receive Offers"],
    },
    {
        "step": 5,
        "title": "Bid submission",
        "description": "Checks that submissions are securely logged, traceable, and handled according to policy.",
        "checkpoints": [
            "Review the submission process",
            "Verify submissions were recorded on receipt as instructed",
            "Verify timestamps for each submission",
            "Identify how recipients of submissions are recorded",
            "Identify where submissions are logged and stored",
            "Review security measures protecting submission integrity",
            "Analyse handling of late submissions",
            "Review the late submission appeal process",
            "Verify process for returning late or non-compliant submissions",
        ],
        "world_bank_alignment": ["Receive Offers"],
    },
    {
        "step": 6,
        "title": "Bid opening",
        "description": "Assesses whether bid openings are transparent, minuted, and corruption-free.",
        "checkpoints": [
            "Analyse the bid opening process including timing and attendance",
            "Verify individuals present and application of evaluation criteria",
            "Assess adherence to guidelines during assessment",
            "Assess adherence to guidelines when making decisions",
            "Assess adherence to guidelines when recording",
            "Assess adherence to guidelines when reporting",
            "Examine incidents of bribery or corruption",
            "Assess process for exclusions, rejections, and barring",
        ],
        "world_bank_alignment": ["Evaluate Offers"],
    },
    {
        "step": 7,
        "title": "Bid evaluation – technical and financial",
        "description": "Validates segregation of technical and financial reviews and evidence-based scoring.",
        "checkpoints": [
            "Verify the approach used for technical submissions",
            "Assess scoring processes and how ties are handled",
            "Verify financial bids remained sealed until technical decisions were final",
            "Verify financial bids for non-compliant technical submissions were returned unopened",
            "Analyse application of bid assessment criteria",
            "Assess fair use of objective assessment",
            "Clarify consistency of approach across bids",
            "Check bids were analysed blind of contractor names",
            "Analyse assessment of subjective criteria",
            "Check that all bid scoring data is recorded",
            "Analyse process for informing successful and unsuccessful bidders",
            "Understand how the market at large was notified of the award",
            "Check anti-corruption measures were applied and recorded",
            "Assess process for managing corruption allegations in evaluation",
        ],
        "world_bank_alignment": ["Evaluate Offers"],
    },
    {
        "step": 8,
        "title": "Authority to incur expenditure",
        "description": "Ensures authority requests mirror tender outcomes and approvals remain traceable.",
        "checkpoints": [
            "Assess compliance with government processes for authority",
            "Verify submissions reflect tender outcomes",
            "Analyse supporting data and evidence",
            "Verify genuine signatures on paperwork",
            "Verify effective filing and reporting of decisions",
            "Check implementation of delivery authority and notifications",
            "Assess communication lines for speed, transparency, and accuracy",
            "Identify evidence of errors and remedial actions",
            "Ensure reporting requirements were completed",
            "Verify delegated authority documentation and validity dates",
            "Assess clarity of delegated authority scope and thresholds",
            "Verify delegated authority letters were not rescinded",
            "Verify system authority thresholds were applied",
        ],
        "world_bank_alignment": ["Award Contract"],
    },
    {
        "step": 9,
        "title": "Tender Board / FEC approval",
        "description": "Confirms Tender Board governance, quorum, and decision tracking.",
        "checkpoints": [
            "Assess structure and process compliance for approvals",
            "Verify submissions reflect tender outcomes",
            "Analyse supporting data and evidence",
            "Confirm quorum and procedural requirements",
            "Confirm clear and minuted decisions",
            "Verify filing and reporting of decisions",
            "Ensure reporting requirements were completed",
            "Confirm implementations align with decisions",
            "Confirm decisions were filed correctly",
        ],
        "world_bank_alignment": ["Award Contract"],
    },
    {
        "step": 10,
        "title": "Contract execution",
        "description": "Monitors delivery, KPI adherence, and remediation across the contract lifecycle.",
        "checkpoints": [
            "Confirm commissioning aligns with Tender Board resolution",
            "Verify implementation followed BPP processes",
            "Assess contract performance against projections",
            "Evaluate in-contract performance versus expectations",
            "Check tolerances and variance thresholds",
            "Assess breach management and invoked measures",
            "Assess issue and communication logs",
            "Verify recorded communications for traceability",
            "Assess resolution methodologies and effectiveness",
            "Analyse root-cause analysis for each issue",
            "Assess lessons learned reporting",
            "Assess stakeholder interactions during the contract",
            "Evaluate KPI reporting levels and criteria",
            "Validate data for bonus or penalties",
            "Assess contract administration quality",
            "Assess measurement of quality, time, and cost",
            "Assess risk process effectiveness and mitigation",
            "Assess budget deviations and root causes",
            "Verify best practices were reported",
            "Assess post-contract lessons learned actions",
            "Ensure reporting requirements were met",
            "Analyse personnel processes on closure",
            "Verify final payments, credits, and queries were addressed",
        ],
        "world_bank_alignment": ["Manage Contract"],
    },
    {
        "step": 11,
        "title": "Continuous review – remedy – redress",
        "description": "Captures post-contract lessons, deltas, and remediation trackers.",
        "checkpoints": [
            "Assess post-contract review process and closeout report",
            "Identify consulted and active personnel",
            "Evaluate post-contract opportunities",
            "Compare initial cost model with final actual costs",
            "Verify discrepancy reports and findings",
            "Assess reasons for cost deltas and actions taken",
            "Ensure contract closure process is complete",
        ],
        "world_bank_alignment": ["Manage Contract"],
    },
]


WORLD_BANK_PUBLISHED_STEPS = [
    "Generate Strategy",
    "Plan Procurement",
    "Invite Offers",
    "Receive Offers",
    "Evaluate Offers",
    "Award Contract",
    "Manage Contract",
]


MONITORING_AND_EVALUATION_FOCUS = [
    "Readiness and completeness of monitoring frameworks",
    "Quality of KPI baselines and targets",
    "Risk management effectiveness and early-warning signals",
    "Sustainability and ESG alignment (UN SDGs)",
    "Use of technology for evidence capture and offline resilience",
]
