"""Domain reference data for procurement audits."""
from __future__ import annotations

from typing import List, TypedDict


class StepChecklist(TypedDict):
    step: int
    title: str
    description: str
    checkpoints: List[str]
    world_bank_alignment: List[str]


class ModuleDefinition(TypedDict):
    """Structured catalog item for high-level modules and sub-modules."""

    code: str
    title: str
    category: str
    description: str
    submodules: List[str]


BPP_NINE_STEPS: List[StepChecklist] = [
    {
        "step": 1,
        "title": "Efficient procurement plan driven by needs assessment",
        "description": "Validates that every procurement initiative starts with a defensible needs statement and structured market strategy.",
        "checkpoints": [
            "Assess the process for identification and justification of the requirement",
            "Analyse the stakeholder management analysis and review",
            "Review the critical needs analysis assessment",
            "Analyse the detailed specification for suitability, openness, and objectivity",
            "Evaluate the strategic analysis process",
            "Assess feasibility and affordability exploration",
            "Assess the process for choosing contract type, structure, and duration",
            "Assess the tender process adopted",
            "Review schedule requirements, milestones, and financing dates",
            "Evaluate the quality expectations set",
            "Assess the risk analysis including appetite, impact, probability, and influencers",
            "Validate the project or contract personnel assigned",
            "Review the market analysis and supplier identification process",
            "Evaluate responsibility matrices, sign-offs, delegations, and RACI formats",
            "Assess geographical or locality issues affecting the contract",
            "Ensure metrics and data sources are clearly identified",
            "Assess reporting and compliance objectives and activities",
            "Analyse ethical compliance considerations and responsibilities",
            "Verify other pertinent or bespoke factors affecting the requirement",
        ],
        "world_bank_alignment": ["Generate Strategy", "Plan Procurement"],
    },
    {
        "step": 2,
        "title": "Budget / Appropriation",
        "description": "Ensures the budget model is evidence-based, validated, and aligned with finance policies and anti-corruption expectations.",
        "checkpoints": [
            "Review the detailed cost model and verify its time validity",
            "Verify authorship and challenge of the model",
            "Assess total cost evaluation, pricing strategy, price security, and VFM factors",
            "Assess whether the model is static, fluid, or future focused",
            "Verify source data and the cost-modelling technique",
            "Assess margins of error, stability parameters, and forecast variance",
            "Evaluate the model against previous models, similar contracts, and experience",
            "Analyse the included cost drivers",
            "Examine currency, levy, tariff, and other international factors",
            "Verify signatures and counter-verification",
            "Verify compliance with finance policies of government and other bodies",
            "Evaluate financial management, accounting, and reporting processes",
            "Assess post-award and post-contract variance along with root-cause analysis",
            "Assess application of anti-corruption, ethical, and World Bank requirements",
            "Analyse the budget process assessment and review cadence",
        ],
        "world_bank_alignment": ["Plan Procurement"],
    },
    {
        "step": 3,
        "title": "Advertisement / Invitation to tender",
        "description": "Confirms opportunity publication is transparent, inclusive, and compliant with equality legislation.",
        "checkpoints": [
            "Analyse the advertisement for clarity, compliance, and openness",
            "Ensure inclusion of all relevant requirement elements",
            "Check compliance with equity, equality, and openness requirements",
            "Verify opportunity publication process, timings, and effectiveness",
            "Verify publication channels such as media, newspapers, and web portals",
            "Verify language and equity requirements were satisfied",
            "Assess management of expressions of interest and pre-approved bidder lists",
        ],
        "world_bank_alignment": ["Invite Offers"],
    },
    {
        "step": 4,
        "title": "Transparent prequalification",
        "description": "Evaluates whether prequalification processes remain objective, time-bound, and well communicated.",
        "checkpoints": [
            "Evaluate the predetermined assessment strategy",
            "Assess criteria for openness and objectivity",
            "Verify publication of the prequalification process and boundaries",
            "Assess data and information sources used for review",
            "Review assessment process, criteria, consistency, and calculations",
            "Assess the quality of evidence provided",
            "Determine if objective criteria were enforced",
            "Analyse prequalification team makeup, structure, and governance",
            "Assess supplier qualification and shortlisting process",
            "Assess requalification records and reporting",
            "Assess query handling, dialogue management, and publicity obligations",
            "Verify issuing methods, ethical management, and information controls",
            "Assess supplier notification style, timing, and content",
            "Assess whether right-of-appeal or resubmission details were provided",
        ],
        "world_bank_alignment": ["Invite Offers", "Receive Offers"],
    },
    {
        "step": 5,
        "title": "Bid submission",
        "description": "Checks that submissions are securely logged, traceable, and handled according to policy.",
        "checkpoints": [
            "Review the submission process",
            "Verify submissions were recorded on receipt as instructed",
            "Verify timestamps for each submission",
            "Identify how recipients of submissions are recorded",
            "Identify where submissions are logged and stored",
            "Review security measures protecting submission integrity",
            "Analyse handling of late submissions",
            "Review the late submission appeal process",
            "Verify process for returning late or non-compliant submissions",
        ],
        "world_bank_alignment": ["Receive Offers"],
    },
    {
        "step": 6,
        "title": "Bid opening",
        "description": "Assesses whether bid openings are transparent, minuted, and corruption-free.",
        "checkpoints": [
            "Analyse the bid opening process including timing and attendance",
            "Verify individuals present and application of evaluation criteria",
            "Assess adherence to guidelines during assessment",
            "Assess adherence to guidelines when making decisions",
            "Assess adherence to guidelines when recording",
            "Assess adherence to guidelines when reporting",
            "Examine incidents of bribery or corruption",
            "Assess process for exclusions, rejections, and barring",
        ],
        "world_bank_alignment": ["Evaluate Offers"],
    },
    {
        "step": 7,
        "title": "Bid evaluation – technical and financial",
        "description": "Validates segregation of technical and financial reviews and evidence-based scoring.",
        "checkpoints": [
            "Verify the approach used for technical submissions",
            "Assess scoring processes and how ties are handled",
            "Verify financial bids remained sealed until technical decisions were final",
            "Verify financial bids for non-compliant technical submissions were returned unopened",
            "Analyse application of bid assessment criteria",
            "Assess fair use of objective assessment",
            "Clarify consistency of approach across bids",
            "Check bids were analysed blind of contractor names",
            "Analyse assessment of subjective criteria",
            "Check that all bid scoring data is recorded",
            "Analyse process for informing successful and unsuccessful bidders",
            "Understand how the market at large was notified of the award",
            "Check anti-corruption measures were applied and recorded",
            "Assess process for managing corruption allegations in evaluation",
        ],
        "world_bank_alignment": ["Evaluate Offers"],
    },
    {
        "step": 8,
        "title": "Authority to incur expenditure",
        "description": "Ensures authority requests mirror tender outcomes and approvals remain traceable.",
        "checkpoints": [
            "Assess compliance with government processes for authority",
            "Verify submissions reflect tender outcomes",
            "Analyse supporting data and evidence",
            "Verify genuine signatures on paperwork",
            "Verify effective filing and reporting of decisions",
            "Check implementation of delivery authority and notifications",
            "Assess communication lines for speed, transparency, and accuracy",
            "Identify evidence of errors and remedial actions",
            "Ensure reporting requirements were completed",
            "Verify delegated authority documentation and validity dates",
            "Assess clarity of delegated authority scope and thresholds",
            "Verify delegated authority letters were not rescinded",
            "Verify system authority thresholds were applied",
        ],
        "world_bank_alignment": ["Award Contract"],
    },
    {
        "step": 9,
        "title": "Tender Board / FEC approval",
        "description": "Confirms Tender Board governance, quorum, and decision tracking.",
        "checkpoints": [
            "Assess structure and process compliance for approvals",
            "Verify submissions reflect tender outcomes",
            "Analyse supporting data and evidence",
            "Confirm quorum and procedural requirements",
            "Confirm clear and minuted decisions",
            "Verify filing and reporting of decisions",
            "Ensure reporting requirements were completed",
            "Confirm implementations align with decisions",
            "Confirm decisions were filed correctly",
        ],
        "world_bank_alignment": ["Award Contract"],
    },
    {
        "step": 10,
        "title": "Contract execution",
        "description": "Monitors delivery, KPI adherence, and remediation across the contract lifecycle.",
        "checkpoints": [
            "Confirm commissioning aligns with Tender Board resolution",
            "Verify implementation followed BPP processes",
            "Assess contract performance against projections",
            "Evaluate in-contract performance versus expectations",
            "Check tolerances and variance thresholds",
            "Assess breach management and invoked measures",
            "Assess issue and communication logs",
            "Verify recorded communications for traceability",
            "Assess resolution methodologies and effectiveness",
            "Analyse root-cause analysis for each issue",
            "Assess lessons learned reporting",
            "Assess stakeholder interactions during the contract",
            "Evaluate KPI reporting levels and criteria",
            "Validate data for bonus or penalties",
            "Assess contract administration quality",
            "Assess measurement of quality, time, and cost",
            "Assess risk process effectiveness and mitigation",
            "Assess budget deviations and root causes",
            "Verify best practices were reported",
            "Assess post-contract lessons learned actions",
            "Ensure reporting requirements were met",
            "Analyse personnel processes on closure",
            "Verify final payments, credits, and queries were addressed",
        ],
        "world_bank_alignment": ["Manage Contract"],
    },
    {
        "step": 11,
        "title": "Continuous review – remedy – redress",
        "description": "Captures post-contract lessons, deltas, and remediation trackers.",
        "checkpoints": [
            "Assess post-contract review process and closeout report",
            "Identify consulted and active personnel",
            "Evaluate post-contract opportunities",
            "Compare initial cost model with final actual costs",
            "Verify discrepancy reports and findings",
            "Assess reasons for cost deltas and actions taken",
            "Ensure contract closure process is complete",
        ],
        "world_bank_alignment": ["Manage Contract"],
    },
]


WORLD_BANK_PUBLISHED_STEPS = [
    "Generate Strategy",
    "Plan Procurement",
    "Invite Offers",
    "Receive Offers",
    "Evaluate Offers",
    "Award Contract",
    "Manage Contract",
]


MONITORING_AND_EVALUATION_FOCUS = [
    "Readiness and completeness of monitoring frameworks",
    "Quality of KPI baselines and targets",
    "Risk management effectiveness and early-warning signals",
    "Sustainability and ESG alignment (UN SDGs)",
    "Use of technology for evidence capture and offline resilience",
]


CORE_AUDIT_MODULES: List[ModuleDefinition] = [
    {
        "code": "A01",
        "title": "Efficient Procurement Plan / Needs Assessment",
        "category": "Core Audit Module",
        "description": "Mirrors BPP Step 1 with granular validation of planning artefacts and governance.",
        "submodules": [
            "Requirement identification & justification",
            "Stakeholder analysis",
            "Critical needs assessment",
            "Specification analysis – suitability, openness, objectivity",
            "Strategic analysis validation",
            "Feasibility & affordability review",
            "Contract type & structure selection",
            "Tender process adoption analysis",
            "Schedule review (timeline, milestones, financing)",
            "Quality expectation analysis",
            "Risk analysis (impact, probability, appetite)",
            "Project personnel validation",
            "Market analysis & supplier identification",
            "Responsibility & RACI validation",
            "Geographical/locality considerations",
            "Metrics & data source clarity",
            "Compliance & reporting structure assessment",
            "Ethical compliance review",
            "Review of special/bespoke factors",
        ],
    },
    {
        "code": "A02",
        "title": "Budget / Appropriation Audit",
        "category": "Core Audit Module",
        "description": "Validates the integrity of funding models, approvals, and anti-corruption controls.",
        "submodules": [
            "Cost model verification",
            "Authorship & review validation",
            "Total cost evaluation & value-for-money assessment",
            "Cost model dynamicity (static/fluid/future)",
            "Data source validation",
            "Variance & forecasting accuracy",
            "Comparison with previous cost models",
            "Cost driver analysis",
            "Currency, levy, tariff & international considerations",
            "Signature & approval verification",
            "Government financial compliance",
            "Financial management & accounting review",
            "Post-award financial delta analysis",
            "Anti-corruption & World Bank compliance",
            "Budget process review",
        ],
    },
    {
        "code": "A03",
        "title": "Advertisement / Invitation to Tender",
        "category": "Core Audit Module",
        "description": "Ensures tender notices are inclusive, comprehensive, and properly distributed.",
        "submodules": [
            "Advertisement content & clarity",
            "Inclusion of all requirement elements",
            "Equality, equity & openness compliance",
            "Publication method & timing verification",
            "Media channel verification (print, portal, web)",
            "Language compliance",
            "EOI & preapproved bidder list management",
        ],
    },
    {
        "code": "A04",
        "title": "Transparent Prequalification",
        "category": "Core Audit Module",
        "description": "Audits supplier filtering discipline, governance, and transparency.",
        "submodules": [
            "Prequalification strategy audit",
            "Criteria objectivity validation",
            "Publication & timing review",
            "Data source verification",
            "Scoring calculation review",
            "Evidence quality assessment",
            "Objectivity of prequalification",
            "Prequalification team assessment",
            "Supplier qualification & shortlisting",
            "Requalification & reporting",
            "Query handling & compliance",
            "Ethical management review",
            "Supplier notification",
            "Appeal/resubmission process",
        ],
    },
    {
        "code": "A05",
        "title": "Bid Submission Audit",
        "category": "Core Audit Module",
        "description": "Scrutinises submission integrity, logging, and exception handling.",
        "submodules": [
            "Submission process review",
            "Recording of received bids",
            "Time/date stamping verification",
            "Recipient identification",
            "Secure logging & storage",
            "Submission integrity/security",
            "Handling of late submissions",
            "Late submission appeals",
            "Return of late/non-compliant bids",
        ],
    },
    {
        "code": "A06",
        "title": "Bid Opening Audit",
        "category": "Core Audit Module",
        "description": "Assures the ceremony follows protocol and remains free of undue influence.",
        "submodules": [
            "Opening process & attendance verification",
            "Persons present validation",
            "Application of guidelines",
            "Decision-making compliance",
            "Recording compliance",
            "Reporting compliance",
            "Bribery & corruption checks",
            "Exclusion/rejection handling",
        ],
    },
    {
        "code": "A07",
        "title": "Bid Evaluation – Technical & Financial",
        "category": "Core Audit Module",
        "description": "Separates technical and financial reviews with robust evidence trails.",
        "submodules": [
            "Technical evaluation methodology",
            "Scoring & tied result management",
            "Financial bid sequence compliance",
            "Incorrect bid opening prevention",
            "Return of unopened bids",
            "Evaluation criteria application review",
            "Objectivity validation",
            "Consistency of evaluation approach",
            "Blind evaluation compliance",
            "Handling of subjective criteria",
            "Data recording of scoring",
            "Notification to bidders",
            "Public notification of awards",
            "Ethical measures verification",
            "Corruption management",
        ],
    },
    {
        "code": "A08",
        "title": "Authority to Incur Expenditure",
        "category": "Core Audit Module",
        "description": "Confirms approvals, delegations, and reporting mirror the tender outcome.",
        "submodules": [
            "Government process compliance",
            "Tender outcome reflection",
            "Evidence supporting authority",
            "Signature verification",
            "Filing & reporting accuracy",
            "Delivery authority processing",
            "Communication transparency",
            "Error logs & remediation",
            "Reporting compliance",
            "Delegated authority validation",
            "Scope & threshold accuracy",
            "Validity & rescind checks",
            "System authority threshold compliance",
        ],
    },
    {
        "code": "A09",
        "title": "Tender Board / FEC Approval",
        "category": "Core Audit Module",
        "description": "Audits governance discipline inside Tender Board or FEC forums.",
        "submodules": [
            "Structure & process compliance",
            "Accuracy of submissions",
            "Verification of evidence",
            "Quorum & procedural compliance",
            "Decision minuting",
            "Filing & reporting",
            "Compliance with reporting requirements",
            "Implementation of decisions",
            "Document filing accuracy",
        ],
    },
    {
        "code": "A10",
        "title": "Contract Execution Audit",
        "category": "Core Audit Module",
        "description": "Monitors delivery quality, KPIs, risk, and remediation throughout execution.",
        "submodules": [
            "Contract commissioning validation",
            "Implementation vs BPP process",
            "Performance vs projection",
            "In-contract performance monitoring",
            "Breach tolerance monitoring",
            "Breach remedial actions",
            "Incident & remedy logs",
            "Communication traceability",
            "Resolution methods audit",
            "Root cause analysis",
            "Lessons learned process",
            "Stakeholder management",
            "KPI reporting audit",
            "Bonus/penalty validation",
            "Contract administration quality",
            "Quality, time & cost tracking",
            "Risk management evaluation",
            "Budget deviation analysis",
            "Best practices reporting",
            "Post-contract learning analysis",
            "Reporting compliance",
            "Personnel/process closeout audit",
            "Final payments reconciliation",
        ],
    },
    {
        "code": "A11",
        "title": "Continuous Review – Remedy – Redress",
        "category": "Core Audit Module",
        "description": "Captures closeout reflections, deltas, and remedy plans.",
        "submodules": [
            "Post-contract review",
            "Review of personnel involved",
            "Post-contract opportunities",
            "Cost model vs actuals comparison",
            "Discrepancy reports",
            "Root cause of variations",
            "Contract closure process audit",
        ],
    },
]


MONITORING_EVALUATION_MODULES: List[ModuleDefinition] = [
    {
        "code": "B01",
        "title": "Monitoring & Evaluation Backbone",
        "category": "Monitoring & Evaluation Module",
        "description": "Cross-cutting capabilities that keep auditors informed in near real-time.",
        "submodules": [
            "Audit dashboard",
            "Benchmarking tools",
            "Contractor historical performance database",
            "Director background checks",
            "Contract lifecycle monitoring",
            "Environmental & ethical compliance monitoring",
            "Predictive analytics (risk, early warnings)",
        ],
    }
]


TECHNICAL_MODULES: List[ModuleDefinition] = [
    {
        "code": "C01",
        "title": "Frontend Module (React.js)",
        "category": "Technical Module",
        "description": "User experience layer for auditors in the field and HQ.",
        "submodules": [
            "Dashboard components",
            "Audit workflow UI",
            "Report viewer",
            "Photo/evidence capture UI",
        ],
    },
    {
        "code": "C02",
        "title": "Backend Module (Python)",
        "category": "Technical Module",
        "description": "Business logic, workflow, and notification services.",
        "submodules": [
            "Microservices architecture",
            "Business rules engine",
            "Audit workflow engine",
            "Notification & logging services",
        ],
    },
    {
        "code": "C03",
        "title": "API Layer",
        "category": "Technical Module",
        "description": "Integration layer for ERP/procurement systems and identity.",
        "submodules": [
            "REST APIs",
            "ERP/procurement system integration",
            "Authentication & RBAC",
        ],
    },
    {
        "code": "C04",
        "title": "AI / ML Module",
        "category": "Technical Module",
        "description": "Advanced analytics to surface anomalies and insights.",
        "submodules": [
            "Anomaly detection",
            "Predictive risk scoring",
            "Supplier performance intelligence",
            "Automated red-flag detection",
        ],
    },
    {
        "code": "C05",
        "title": "Database Module",
        "category": "Technical Module",
        "description": "Data persistence across structured, semi-structured, and log stores.",
        "submodules": [
            "PostgreSQL (structured audit data)",
            "MongoDB (documents, evidence, contracts)",
            "Audit trail & log storage",
        ],
    },
    {
        "code": "C06",
        "title": "Cloud & Infrastructure",
        "category": "Technical Module",
        "description": "Deployment, resiliency, and offline sync tooling.",
        "submodules": [
            "AWS / Azure deployment",
            "Auto-backup & offline sync",
            "Local device caching for low connectivity",
        ],
    },
    {
        "code": "C07",
        "title": "Security Module",
        "category": "Technical Module",
        "description": "Controls to meet BPP, World Bank, and international security expectations.",
        "submodules": [
            "Multi-factor authentication",
            "Role-based access control",
            "Data encryption (configurable)",
            "Secure evidence storage",
        ],
    },
]


SUPPORTING_MODULES: List[ModuleDefinition] = [
    {
        "code": "D01",
        "title": "Supporting Services",
        "category": "Supporting Module",
        "description": "Additional capabilities that improve auditor effectiveness and data richness.",
        "submodules": [
            "Evidence capture (photos, notes, attachments)",
            "Offline mode & sync engine",
            "Reporting & export (PDF/Excel)",
            "Auditor authentication & device management",
            "Historical data repository",
            "Contractor & director intelligence database",
        ],
    }
]


MODULE_CATALOG = {
    "core": CORE_AUDIT_MODULES,
    "monitoring": MONITORING_EVALUATION_MODULES,
    "technical": TECHNICAL_MODULES,
    "supporting": SUPPORTING_MODULES,
}
